const BASE_STYLE = "Civilisation ARA pre-diluvienne. Palette: beige froid, gris perle, pierre chaude, sable sombre, bleu eau efface, cuivre noirci, ivoire fume, noir mat. Lumiere analytique maitrisee. Matieres: geopolymeres mineraux, pierre ancienne, verre epais, cuivre assombri, ceramiques veinees, fibres tendues. Beaute par accord et fonction. Rendu photorealiste cinematographique, noble, grave, mineral."

const ARU_DESC = "Meme personnage ARU-NAEL: homme grande stature, peau brun-cendre reflets cuivres, visage long traits nobles, pommettes nettes, nez droit, yeux sombres. Cheveux nattes anneau metal mat. Sur-tunique gris nuit, tunique ecrue col droit, ceinture cuir noir, bandes bleu aux poignets."
const MAEL_DESC = "Meme personnage MAEL-IRA: femme peau brune chaude, longues tresses hautes. Tissus mineraux argile gris perle bleu eau. Grace fonctionnelle."
const KAEL_DESC = "Meme personnage KAEL: homme sec mobile beaute austere. Peau brun clair, traits nets, pommettes hautes, cheveux noirs tresses nuque. Manteau long fendu sable sombre ombres bleutees, brassards alliage mat."
const THO_DESC = "Meme personnage THO-AN: homme masse calme. Peau ambree, yeux sombres tres fixes, nez fort, pommettes larges. Cheveux noirs anneaux cuivre noirci longues meches epaules. Manteau sans manches toile minerale pierre chaude."
const RAKHAN_DESC = "Meme personnage RA-KHAN: homme peau sombre, crane ras, balafre machoire, traits larges. Armure souple brun-noir plaques mates bottes hautes."
const ENA_DESC = "Meme personnage ENA: femme claire grave. Peau cuivree claire, cheveux noirs lies bas, visage fin stable. Robe ivoire fume, voile lecture bleu pale."

export const CHARACTERS = [
  {
    id: 'aru-nael',
    name: 'ARU-NAËL',
    role: 'Régulateur supérieur',
    location: 'Talar',
    images: [
      {
        id: 'aru-1',
        label: 'Portrait référence',
        ratio: '2:3',
        isRef: true,
        prompt: `Portrait frontal. Homme grande stature, peau brun-cendre reflets cuivrés, visage long traits nobles, pommettes nettes, nez droit, yeux sombres. Cheveux nattés anneau métal mat. Sur-tunique gris nuit, tunique écrue col droit, ceinture cuir noir, bandes bleu aux poignets. Fond Talar pierre claire, lumière analytique froide. ${BASE_STYLE}`,
      },
      {
        id: 'aru-2',
        label: 'Bassin primaire',
        ratio: '2:3',
        isRef: false,
        prompt: `ARU-NAËL accroupi bord bassin primaire Talar. Eau immobile anormale. Globes de mesure suspendus. Lumière matinale. ${ARU_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'aru-3',
        label: 'Tablette minérale',
        ratio: '2:3',
        isRef: false,
        prompt: `ARU-NAËL tenant tablette minérale inclinée. Surface révèle courbes correspondances. Expression lit valeur identique trois cycles. ${ARU_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'aru-4',
        label: 'Seuil du Conseil',
        ratio: '2:3',
        isRef: false,
        prompt: `ARU-NAËL franchissant seuil salles Conseil Talar. Porte monumentale minérale. Posture sobre souveraine. ${ARU_DESC} ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'mael-ira',
    name: 'MAËL-IRA',
    role: 'Régulatrice des flux',
    location: 'Vara-Ind',
    images: [
      {
        id: 'mael-1',
        label: 'Portrait référence',
        ratio: '2:3',
        isRef: true,
        prompt: `Portrait frontal. Femme rivage bassin grâce fonctionnelle. Peau brune chaude, longues tresses hautes. Tissus minéraux argile gris perle bleu eau. Fond Vara-Ind, lumière aube humide. ${BASE_STYLE}`,
      },
      {
        id: 'mael-2',
        label: 'Plateforme orientale',
        ratio: '2:3',
        isRef: false,
        prompt: `MAËL-IRA debout plateforme orientale pieds nus basalte clair. Yeux mi-clos écoute profonde. Terrasses hydrauliques gradins. Aube. ${MAEL_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'mael-3',
        label: 'Tablette composite',
        ratio: '2:3',
        isRef: false,
        prompt: `MAËL-IRA mains sur tablette composite anormalement sèche. Expression légère inquiétude. Gros plan mi-corps. ${MAEL_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'mael-4',
        label: 'Bassins en gradins',
        ratio: '2:3',
        isRef: false,
        prompt: `MAËL-IRA profil observant bassins en gradins Vara-Ind. Posture autorité organique. ${MAEL_DESC} ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'kael',
    name: 'KAËL',
    role: 'Navigateur de grand rayon',
    location: 'Ora-Mu',
    images: [
      {
        id: 'kael-1',
        label: 'Portrait référence',
        ratio: '2:3',
        isRef: true,
        prompt: `Portrait frontal. Homme sec mobile beauté austère. Peau brun clair, traits nets, pommettes hautes, cheveux noirs tressés nuque. Manteau long fendu sable sombre ombres bleutées, brassards alliage mat. Lumière marine Ora-Mu. ${BASE_STYLE}`,
      },
      {
        id: 'kael-2',
        label: 'Terrasse arrimage',
        ratio: '2:3',
        isRef: false,
        prompt: `KAËL terrasse haute aire arrimage Ora-Mu. Regard vimanas en préparation. Falaises mer. ${KAEL_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'kael-3',
        label: 'Coursive sud',
        ratio: '2:3',
        isRef: false,
        prompt: `KAËL coursive sud Ora-Mu face jeune navigateur. Pierre noire autour. ${KAEL_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'kael-4',
        label: 'Navigation vimana',
        ratio: '2:3',
        isRef: false,
        prompt: `KAËL navigation bord vimana. Mains interface tablette ciel. Chambre sombre nacrée. ${KAEL_DESC} ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'tho-an',
    name: 'THO-AN',
    role: 'Architecte de profondeur',
    location: 'An-Ka',
    images: [
      {
        id: 'tho-1',
        label: 'Portrait référence',
        ratio: '2:3',
        isRef: true,
        prompt: `Portrait frontal. Homme plateau masse calme. Peau ambrée, yeux sombres très fixes, nez fort, pommettes larges. Cheveux noirs anneaux cuivre noirci longues mèches épaules. Manteau sans manches toile minérale pierre chaude. Lumière dure An-Ka. ${BASE_STYLE}`,
      },
      {
        id: 'tho-2',
        label: 'Garde-corps composite',
        ratio: '2:3',
        isRef: false,
        prompt: `THO-AN main sur garde-corps composite bleuté An-Ka. Pierre répond mémoire contrainte. ${THO_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'tho-3',
        label: 'Tablette trois lames',
        ratio: '2:3',
        isRef: false,
        prompt: `THO-AN observant tablette trois lames déployées. Lignes charge visibles. ${THO_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'tho-4',
        label: 'Berceaux lithiques',
        ratio: '2:3',
        isRef: false,
        prompt: `THO-AN devant berceaux lithiques vimanas altitude An-Ka. Coques renforcées derrière. ${THO_DESC} ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'ra-khan',
    name: 'RA-KHAN',
    role: 'Gardien de frontière',
    location: 'Ka-Ur',
    images: [
      {
        id: 'rakhan-1',
        label: 'Portrait référence',
        ratio: '2:3',
        isRef: true,
        prompt: `Portrait frontal. Peau sombre, crâne ras, balafre mâchoire, traits larges. Armure souple campagne brun-noir plaques mates bottes hautes. Lumière sèche Ka-Ur. ${BASE_STYLE}`,
      },
      {
        id: 'rakhan-2',
        label: 'Poste crête',
        ratio: '2:3',
        isRef: false,
        prompt: `RA-KHAN poste crête Ka-Ur. Vue territoire pierre rousse. ${RAKHAN_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'rakhan-3',
        label: 'Distribution rations',
        ratio: '2:3',
        isRef: false,
        prompt: `RA-KHAN distribution couloirs ration Ka-Ur. ${RAKHAN_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'rakhan-4',
        label: 'Silhouette nocturne',
        ratio: '2:3',
        isRef: false,
        prompt: `RA-KHAN silhouette nuit crête Ka-Ur. Ciel étoilé. ${RAKHAN_DESC} ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'ena',
    name: 'ENA',
    role: 'Archiviste de la Mémoire',
    location: 'Elen-Ar',
    images: [
      {
        id: 'ena-1',
        label: 'Portrait référence',
        ratio: '2:3',
        isRef: true,
        prompt: `Portrait frontal. Femme claire grave. Peau cuivrée claire, cheveux noirs liés bas, visage fin stable. Robe ivoire fumé, voile lecture bleu pâle. Fond Elen-Ar pierre pâle, lumière amortie. ${BASE_STYLE}`,
      },
      {
        id: 'ena-2',
        label: 'Cylindre archival',
        ratio: '2:3',
        isRef: false,
        prompt: `ENA ouvrant cylindre archival salle des strates Elen-Ar. Tables elliptiques autour. ${ENA_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'ena-3',
        label: 'Texte fondateur',
        ratio: '2:3',
        isRef: false,
        prompt: `ENA lisant voix basse texte fondateur. Ilys de profil arrière-plan. ${ENA_DESC} ${BASE_STYLE}`,
      },
      {
        id: 'ena-4',
        label: 'Escalier chambres basses',
        ratio: '2:3',
        isRef: false,
        prompt: `ENA descendant escalier chambres basses Elen-Ar, lames et cylindre tenus. ${ENA_DESC} ${BASE_STYLE}`,
      },
    ],
  },
]

export const VILLES = [
  {
    id: 'talar',
    name: 'TALAR',
    role: 'Capitale lecture systémique',
    location: '',
    images: [
      {
        id: 'talarv-1',
        label: 'Vue aérienne',
        ratio: '16:9',
        isRef: true,
        prompt: `Vue aérienne TALAR. Ville plateaux axes civiques horizontale. Pierre claire beige froid gris perle cuivre assombri. Terrasses vers mer paliers. Bassins régulation passerelles tours courtes. Vimanas. Lumière claire analytique. ${BASE_STYLE}`,
      },
      {
        id: 'talarv-2',
        label: 'Bassin primaire',
        ratio: '16:9',
        isRef: false,
        prompt: `TALAR bassin primaire analyse. Anneau pierre sombre veiné argent. Globes mesure suspendus. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'talarv-3',
        label: 'Salle convergence',
        ratio: '16:9',
        isRef: false,
        prompt: `TALAR salle convergence. Carte volumétrique planète suspendue. Haute baie mer. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'vara-ind',
    name: 'VARA-IND',
    role: 'Ville hydraulique majeure',
    location: '',
    images: [
      {
        id: 'varaindv-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `VARA-IND vue ensemble. Terrasses hydrauliques gradins canaux disciplinés. Basalte clair pierre argile eau gris-bleu. Lumière aube humide. ${BASE_STYLE}`,
      },
      {
        id: 'varaindv-2',
        label: 'Plateforme orientale',
        ratio: '16:9',
        isRef: false,
        prompt: `VARA-IND plateforme orientale. Disque basalte veiné. Aube. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'varaindv-3',
        label: 'Bassins internes',
        ratio: '16:9',
        isRef: false,
        prompt: `VARA-IND bassins internes vannes minérales. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'ora-mu',
    name: 'ORA-MU',
    role: 'Ville du ciel et des arrimages',
    location: '',
    images: [
      {
        id: 'oramuv-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `ORA-MU vue ensemble. Terrasses hautes falaises côtières. Pierre noire ivoire mat. Vimanas berceaux et vol. Lumière marine embruns. ${BASE_STYLE}`,
      },
      {
        id: 'oramuv-2',
        label: 'Plateforme arrimage',
        ratio: '16:9',
        isRef: false,
        prompt: `ORA-MU plateforme arrimage. Rainures berceaux vimanas. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'oramuv-3',
        label: 'Vimana décollant',
        ratio: '16:9',
        isRef: false,
        prompt: `ORA-MU vimana décollant. Coque sombre nacrée. Mer falaises. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'an-ka',
    name: 'AN-KA',
    role: 'Ville architecturale de plateau',
    location: '',
    images: [
      {
        id: 'ankav-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `AN-KA vue ensemble haut plateau. Plateformes trapézoïdales ponts minéraux puits axe. Pierre chaude gris bleu cuivre noirci. Lumière dure air sec. ${BASE_STYLE}`,
      },
      {
        id: 'ankav-2',
        label: 'Terrasse noyaux',
        ratio: '16:9',
        isRef: false,
        prompt: `AN-KA terrasse noyaux. Volumes étagés garde-corps composite bleuté. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'ankav-3',
        label: 'Puits axe profond',
        ratio: '16:9',
        isRef: false,
        prompt: `AN-KA puits axe profond. Chambres charge profondes anneaux pierre. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'ka-ur',
    name: 'KA-UR',
    role: 'Ville frontière',
    location: '',
    images: [
      {
        id: 'kaurv-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `KA-UR vue ensemble. Crêtes plaines routes convoi. Pierre rousse sable compacté métal mat. Lumière sèche poussière vent. ${BASE_STYLE}`,
      },
      {
        id: 'kaurv-2',
        label: 'Poste crête',
        ratio: '16:9',
        isRef: false,
        prompt: `KA-UR poste crête. Territoire frontière. Gardiens silhouettes. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'kaurv-3',
        label: 'Nuit étoilée',
        ratio: '16:9',
        isRef: false,
        prompt: `KA-UR nuit. Ciel étoilé. Vimana surveillance discret. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'elen-ar',
    name: 'ELEN-AR',
    role: 'Ville de mémoire et archives',
    location: '',
    images: [
      {
        id: 'elenarv-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `ELEN-AR vue ensemble. Salles longues cours ombre lumière galeries suspendues bassins silencieux. Pierre pâle ivoire fumé. Lumière très amortie atmosphère fraîche. ${BASE_STYLE}`,
      },
      {
        id: 'elenarv-2',
        label: 'Salle des strates',
        ratio: '16:9',
        isRef: false,
        prompt: `ELEN-AR salle des strates. Table elliptique plaques superposées puits fraîcheur. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'elenarv-3',
        label: 'Chambre basse',
        ratio: '16:9',
        isRef: false,
        prompt: `ELEN-AR chambre basse recoupements. Tables anciennes. Lumière très rare fraîcheur profonde. Meme architecture, meme palette que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
]

export const VIMANAS = [
  {
    id: 'vima-liaison',
    name: 'LIAISON',
    role: 'Correspondance et décision rapide',
    location: 'Ora-Mu / Talar',
    images: [
      {
        id: 'vima-liaison-1',
        label: 'Vue référence',
        ratio: '16:9',
        isRef: true,
        prompt: `Vimana de liaison ARA. Coque fine longue accordée. Joints précis, matériaux sombres nacrés, anneaux de stabilisation lisibles, membranes de portance discrètes. Vue latérale complète. Berceau minéral Ora-Mu, fond marine. ${BASE_STYLE}`,
      },
      {
        id: 'vima-liaison-2',
        label: 'En vol',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana liaison ARA en vol haute altitude. Trajectoire calme souveraine. Ciel clair analytique. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'vima-liaison-3',
        label: 'Arrimage Talar',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana liaison ARA en arrimage berceau minéral Talar. Rainures accueil, lignes recalibrage. Personnel technique silhouettes. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'vima-porteur',
    name: 'PORTEUR MIXTE',
    role: 'Transport hommes et matières sensibles',
    location: 'Ora-Mu / routes hautes',
    images: [
      {
        id: 'vima-porteur-1',
        label: 'Vue référence',
        ratio: '16:9',
        isRef: true,
        prompt: `Vimana porteur mixte ARA. Ventre large, nervures latérales, stabilité renforcée. Coque sombre nacrée, joints précis, anneaux compartimentés. Vue latérale. Plateforme Ora-Mu falaises marines. ${BASE_STYLE}`,
      },
      {
        id: 'vima-porteur-2',
        label: 'En vol chargé',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana porteur mixte ARA en vol chargé. Horizon mer falaises. Coque basse portante. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'vima-porteur-3',
        label: 'Déchargement plateforme',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana porteur mixte ARA déchargement matières sensibles plateforme d'arrimage. Silhouettes techniques au travail. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'vima-surveillance',
    name: 'SURVEILLANCE FRONTIÈRE',
    role: 'Observation et contrôle territorial',
    location: 'Ka-Ur / marges',
    images: [
      {
        id: 'vima-surv-1',
        label: 'Vue référence',
        ratio: '16:9',
        isRef: true,
        prompt: `Vimana de surveillance frontière ARA. Compact, tactique, accès rapide. Coque sombre mate, profil discret, anneaux minimes. Vue latérale. Crête Ka-Ur pierre rousse lumière sèche. ${BASE_STYLE}`,
      },
      {
        id: 'vima-surv-2',
        label: 'En vol territoire',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana surveillance ARA en vol bas territoire frontière. Pierre rousse sable compacté en dessous. Discrétion autorité. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'vima-surv-3',
        label: 'Veille nocturne',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana surveillance ARA amarré crête Ka-Ur nuit. Ciel étoilé. Gardien silhouette. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'vima-altitude',
    name: 'ALTITUDE / PLATEAU',
    role: 'Passages trans-chaînes et logistique haute terre',
    location: 'An-Ka',
    images: [
      {
        id: 'vima-alti-1',
        label: 'Vue référence',
        ratio: '16:9',
        isRef: true,
        prompt: `Vimana altitude plateau ARA. Structure recalibrée pour chaînes et vents secs. Renforts latéraux, coque pierre chaude gris bleu, anneaux de retenue renforcés. Vue latérale. Berceau lithique An-Ka haut plateau lumière dure. ${BASE_STYLE}`,
      },
      {
        id: 'vima-alti-2',
        label: 'En vol haute montagne',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana altitude ARA en vol passages trans-chaînes. Masses rocheuses haute altitude autour. Air sec lumière dure. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'vima-alti-3',
        label: 'Arrimage An-Ka',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana altitude ARA arrimage berceau lithique An-Ka. Coques renforcées autour. Altitude, lumière oblique sèche. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'vima-crise',
    name: 'VECTEUR DE CRISE',
    role: 'Charges exceptionnelles — usage doctrinal rare',
    location: 'Enceintes fermées',
    images: [
      {
        id: 'vima-crise-1',
        label: 'Vue référence',
        ratio: '16:9',
        isRef: true,
        prompt: `Vimana vecteur de crise ARA. Coque épaisse compartimentée, signes techniques denses gravés, chambres scellées visibles, anneaux de contention. Vue latérale. Enceinte fermée arsenal profond, lumière très rare. ${BASE_STYLE}`,
      },
      {
        id: 'vima-crise-2',
        label: 'Chambre intérieure',
        ratio: '16:9',
        isRef: false,
        prompt: `Intérieur vimana vecteur de crise ARA. Chambre compartimentée sombre, interfaces scellées, signes techniques gravés, gravité d'installation. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'vima-crise-3',
        label: 'Sortie enceinte',
        ratio: '16:9',
        isRef: false,
        prompt: `Vimana vecteur de crise ARA sortant enceinte fermée. Autorité froide, lenteur souveraine. Portes massives minérales. Meme vimana que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
]

export const LIEUX = [
  {
    id: 'lieu-arrimage',
    name: 'PLATEFORME D\'ARRIMAGE',
    role: 'Infrastructure d\'accueil des vimanas',
    location: 'Ora-Mu',
    images: [
      {
        id: 'lieu-arrimage-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `Plateforme d'arrimage ARA. Grande surface pierre noire sombre. Rainures d'accueil, berceaux minéraux, lignes de recalibrage, accès de maintenance. Vimanas en approche. Lumière marine Ora-Mu embruns. ${BASE_STYLE}`,
      },
      {
        id: 'lieu-arrimage-2',
        label: 'Détail berceau',
        ratio: '16:9',
        isRef: false,
        prompt: `Détail berceau minéral plateforme arrimage ARA. Rainures précises, joints fonctionnels, techniciens silhouettes maintenance. Meme lieu que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'lieu-bassin',
    name: 'BASSIN DE RÉGULATION',
    role: 'Lecture des flux et régulation des masses liquides',
    location: 'Vara-Ind',
    images: [
      {
        id: 'lieu-bassin-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `Bassin de régulation ARA. Gradins, chambres de ralentissement, eau disciplinée gris-bleu. Échange thermique visible. Architectures de retenue minérales. Lumière aube humide Vara-Ind. ${BASE_STYLE}`,
      },
      {
        id: 'lieu-bassin-2',
        label: 'Vannes minérales',
        ratio: '16:9',
        isRef: false,
        prompt: `Détail vannes minérales bassin régulation ARA. Reflets eau calme disciplinée. Lecture flux, métal sombre lignes fines. Meme lieu que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'lieu-lecture',
    name: 'SALLE DE LECTURE',
    role: 'Analyse systémique et interfaces de décision',
    location: 'Talar',
    images: [
      {
        id: 'lieu-lecture-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `Salle de lecture systémique ARA Talar. Tables d'alignement, reliefs, surfaces gravées, pigments sensibles. Lumière de précision analytique. Opérateurs silhouettes concentrés. ${BASE_STYLE}`,
      },
      {
        id: 'lieu-lecture-2',
        label: 'Interface tablette',
        ratio: '16:9',
        isRef: false,
        prompt: `Détail tablette minérale active salle de lecture ARA. Surface gravée lumineuse, mains opérateur protocole rigoureux. Meme lieu que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'lieu-noyau',
    name: 'NOYAU / CHAMBRE DE CHARGE',
    role: 'Médiation des contraintes structurelles',
    location: 'An-Ka',
    images: [
      {
        id: 'lieu-noyau-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `Noyau chambre de charge ARA An-Ka. Cœur profond plateau. Anneaux pierre accordée, vides latéraux, médiation contraintes visible. Pierre chaude gris bleu cuivre noirci. Lumière dure rare. ${BASE_STYLE}`,
      },
      {
        id: 'lieu-noyau-2',
        label: 'Puits axe',
        ratio: '16:9',
        isRef: false,
        prompt: `Puits axe profond noyau ARA An-Ka. Profondeur vertigineuse, anneaux pierre successifs, lumière très rare oblique. Meme lieu que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'lieu-archive',
    name: 'ARCHIVE / SALLE DES STRATES',
    role: 'Conservation de la mémoire et recoupements',
    location: 'Elen-Ar',
    images: [
      {
        id: 'lieu-archive-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `Salle des strates archives ARA Elen-Ar. Tables elliptiques plaques superposées, cylindres archivaux, puits de fraîcheur. Lumière très amortie atmosphère fraîche stratifiée. Pierre pâle ivoire fumé. ${BASE_STYLE}`,
      },
      {
        id: 'lieu-archive-2',
        label: 'Cylindres archivaux',
        ratio: '16:9',
        isRef: false,
        prompt: `Rangées cylindres archivaux ARA Elen-Ar. Protocole d'accès, mains archiviste, atmosphère calme fraîche profonde. Meme lieu que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'lieu-seuil',
    name: 'POSTE DE SEUIL',
    role: 'Contrôle des passages et distributions',
    location: 'Ka-Ur',
    images: [
      {
        id: 'lieu-seuil-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `Poste de seuil ARA Ka-Ur. Contrôle territorial, citernes, couloirs de ration, structures de passage. Pierre rousse sable compacté métal mat. Lumière sèche poussière vent. ${BASE_STYLE}`,
      },
      {
        id: 'lieu-seuil-2',
        label: 'Couloir de ration',
        ratio: '16:9',
        isRef: false,
        prompt: `Couloir de ration poste seuil ARA Ka-Ur. Distribution disciplinée, gardiens silhouettes, salle de confinement fond. Meme lieu que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
  {
    id: 'lieu-arsenal',
    name: 'ARSENAL DE PROFONDEUR',
    role: 'Enceinte des armes doctrinales',
    location: 'Enceintes fermées',
    images: [
      {
        id: 'lieu-arsenal-1',
        label: 'Vue ensemble',
        ratio: '16:9',
        isRef: true,
        prompt: `Arsenal de profondeur ARA. Volume fermé claustral. Matériaux sombres très denses, chambre d'interface, signes techniques gravés pouvoir retenu. Lumière rarissime. Sentiment gravité absolue. ${BASE_STYLE}`,
      },
      {
        id: 'lieu-arsenal-2',
        label: 'Chambre interface',
        ratio: '16:9',
        isRef: false,
        prompt: `Chambre interface arsenal profondeur ARA. Tiges d'accès, matrices scellées, protocole de retenue. Chaleur contenue lumière rare. Meme lieu que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
]

export const ARMES = [
  {
    id: 'armes-terribles',
    name: 'ARMES TERRIBLES',
    role: 'Extrémités doctrinales — usage rarissime',
    location: 'Arsenaux de profondeur',
    images: [
      {
        id: 'arme-1',
        label: 'Gaine minérale',
        ratio: '16:9',
        isRef: true,
        prompt: `Arme terrible ARA. Gaine minérale sombre, chambre de contention, tiges d'interface gravées, matrice de focalisation. Signes techniques denses. Enceinte profonde, lumière très rare. Chaleur contenue, puissance tenue — jamais de spectacle. ${BASE_STYLE}`,
      },
      {
        id: 'arme-2',
        label: 'Arsenal rangées',
        ratio: '16:9',
        isRef: false,
        prompt: `Rangées gaines armes terribles ARA arsenal profondeur. Protocole accès strict, matériaux sombres claustraux. Sentiment puissance tenue retenue absolue. Meme objets que vue reference. ${BASE_STYLE}`,
      },
      {
        id: 'arme-3',
        label: 'Interface scellée',
        ratio: '16:9',
        isRef: false,
        prompt: `Interface scellée arme terrible ARA. Matrice gravée, accès protocole lourd, gravité d'installation. Lumière rarissime chaleur minime contenue. Meme objets que vue reference. ${BASE_STYLE}`,
      },
    ],
  },
]
